### ISSUE TITLE
There is a problem after the May 28th update

### ISSUE THREAD

**Issue by ferutospencer** [Kimjio/umamusume-localify#13]
I can't run the game after this update, unless I remove [umamusume-localify]

**Comment by Kimjio** [comment]
![2024-05-28 (3)](https://github.com/Kimjio/umamusume-localify/assets/10695980/99ffd017-2560-41bf-81f3-8f9fff992927)
When hooking Application::Quit(), it was confirmed that it continued without terminating.

I will update you after I find the appropriate solution.

**Comment by ferutospencer** [comment]
thank you  so much :)
