### ISSUE TITLE
Question about the usage

### ISSUE THREAD

**Issue by Hacinsl** [Kimjio/umamusume-localify#17]
(I know this issue may look silly, but I......miss my umamusume!)
The plugin seemed to have changed the injection method because https://github.com/Kimjio/umamusume-localify/issues/16. I got a file named `UnityPlayer.dll`(1272kb) after cloned the code and compiled it with vs2022, but I had no idea how to use it......
Simply replacing the origin `UnityPlayer.dll` with it will cause the failure of the launch (showing as nothing happen after I launch in DMM) . DMM will download a new `UnityPlayer.dll` and cover my file.
Is this because the update is still working in progress? Or just because I used the dll wrongly? Thanks!

**Comment by yushenzc** [comment]
localify can start the game without the dmm games player,did you try it?

**Comment by Hacinsl** [comment]
> localify can start the game without the dmm games player,did you try it?

Do you mean directly run umamusume.exe with the generated UnityPlayer.dll? I tried but nothing happened.
My folder looks like this:
![QQ截图20241214223604](https://github.com/user-attachments/assets/dcdb108d-d2ed-422e-a0b9-3b47523ba711)

**Comment by Kimjio** [comment]
A new release has been published.
Since this version has been changed to inject via DLL redirection, you need to apply the command below on the first run.

```cmd
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options" /v DevOverrideEnable /t REG_DWORD /d 1
```
