### ISSUE TITLE
LookAt and Physics issue in high-res

### ISSUE THREAD

**Issue by RabberDakk** [Kimjio/umamusume-localify#6]
I'm rendering at 4K or more, there are 2 problem.

1) LookAt not working
2) physics behaving strangely

These problems existed in the original old `umamusume-localify`, but was fixed at some point and recurred again when the original `umamusume-localify` stopped working. Is there any way to fix this problem?

**Correct (non high-res)**
<img src="https://user-images.githubusercontent.com/59415461/212462063-08be1830-30d4-412a-a161-47b0c5121b2d.jpg" width="400px">

**Incorrect (high-res)**
<img src="https://user-images.githubusercontent.com/59415461/212462069-72ac993f-de11-4c10-8ec0-01e343a5c91f.jpg" width="400px">

```json
{
  "enableConsole": true,
  "autoOpenBrowser": false,
  "maxFps": 0,
  "uiScale": 4.0,
  "replaceFont": false,
  "resolution3dScale": 1.0,
  "autoFullscreen": false,
  "unlockSize": true,
  "enableLogger": true
}
```

Version: 1.14.1

**Comment by Kimjio** [comment]
1 and 2 are all frame related issues.

1. Do not set `maxFps` to `0` (unlimited). I know this is a problem that has existed before.
![2023-01-17 (1)](https://user-images.githubusercontent.com/10695980/212738559-bb348b7e-c837-4c6d-98d1-db2eda46db19.png)
This is the screen that comes out without problems when `maxFps` is set to `60` at 4K resolution.

2. Physics behavior is based on 30FPS.
It operates through a library called CySpring, and the default update mode is based on 30FPS.
Added option to change CySpring update mode (`cySpringUpdateMode`), setting it to `1` (Enum name: Mode60FPS) will improve most physics behavior. (Don't set it to `2` or `3` unless you want to see something weird.)

**Comment by RabberDakk** [comment]
![212546719-c346e4fa-5415-43f7-990e-460103f55327](https://user-images.githubusercontent.com/59415461/212746048-ef3050f1-7364-4dcd-a398-2912d217f623.gif)

all issues have been resolved 🙏 
```json
{
  "enableConsole": true,
  "autoOpenBrowser": false,
  "maxFps": 60,
  "cySpringUpdateMode": 1,
  "uiScale": 4.0,
  "replaceFont": false,
  "resolution3dScale": 1.0,
  "autoFullscreen": true,
  "unlockSize": true,
  "enableLogger": true
}
```
