### ISSUE TITLE
Font replacement is forced.

### ISSUE THREAD

**Issue by reindex-ot** [Kimjio/umamusume-localify#7]
Fonts are replaced even if the option is set to false.

**Comment by Kimjio** [comment]
Set `replaceToBuiltinFont` instead of `replaceFont`

**Comment by reindex-ot** [comment]
I have changed the options, but it still seems to be forced to replace it.

**Comment by Kimjio** [comment]
Could you please share your config.json?

**Comment by reindex-ot** [comment]
ok.

`{
    "enableConsole": false,
    "enableLogger": false,
    "dumpStaticEntries": false,
    "maxFps": 60,
    "unlockSize": false,
    "uiScale": 1.0,
    "autoFullscreen": ture,
    "replaceToBuiltinFont": false,
    "dicts": []
}`

![umamusume_font](https://user-images.githubusercontent.com/32851879/221370471-b7320d54-2280-4e1f-9c93-863a9a98d264.png)

**Comment by Kimjio** [comment]
```json
{ "enableConsole": false, "enableLogger": false, "dumpStaticEntries": false, "maxFps": 60, "unlockSize": false, "uiScale": 1.0, "autoFullscreen": ture, "replaceToBuiltinFont": false, "dicts": [] }
```

This issue occurs because config.json could not be parsed because the value of `autoFullscreen` was incorrectly entered as `ture`.

Improved to display a message box when a JSON parsing error occurs to inform you of the problem.

**Comment by reindex-ot** [comment]
The font issue has been resolved, thanks also for the notification implementation regarding the json description.
